//
//  DataStore.swift
//  Motiv8me
//
//  Copyright © 2018-2019 Ted Presley. All rights reserved.
//

import Foundation

struct DataStore {
  static let images = ["ocean", "bridge", "city", "fence", "road", "sunset", "trail", "train", "newyork", "rails", "river", "valley", "waves", "paris", "rocky", "dock", "nyc", "mountriver", "stars", "air", "boardwalk", "stars2", "brick", "wood-bridge", "bluestars", "cosmic", "mountains", "ocean2", "sea"]
  
  static let quotes = ["Life isn\'t about getting and having, it\'s about giving and being", "You can never cross the ocean until you have the courage to lose sight of the shore", "Your time is limited, so don\'t waste it living someone else\'s life.", "Time is the most valuable thing you can spend", "Smiling is the best way to start your day", "Time spent laughing is time well spent", "Mistakes are proof you are trying", "Every accomplishment starts with the decision to try", "The longest journey always begins with one, simple step", "Time flies, but you are the pilot", "Don\'t always look backwards or you will miss your future", "When was the last time you did something for the first time?", "Every dawn brings new hope, every dusk should bring satisfaction", "Don\'t count the minutes of the day. Make the minutes of the day count.", "Stand up and say, \"I will be great today!\"", "The time is always right to do the right thing now", "The only thing we all have in common is the same hours in a day", "Sometimes good things fall apart so better things can fall together", "Brighten someone else\'s day and it will warm your soul", "By small and simple things are great things brought to pass", "Today is a new day", "Be glad life doesn\'t come with an instruction manual", "It is way more fun to wing it than to follow directions", "Your life should not be a game of follow the leader, pave your own path", "Your days are as fun as you make them", "Life goes on so keep on keeping on!", "Smile. You\'re beautiful", "Don\'t fall back on what\'s behind you, spring forward to what\'s ahead", "Do one thing every day that will make someone smile", "Dreams bloom best in a well tended garden", "When life gives you lemons ask, \"Is that ALL you\'ve got?\"", "When it\'s cloudy remember, the sun is always shining somewhere", "Life is a party, don\'t forget to bring the cake!", "Learn from yesterday, dream about tomorrow, live in the moment", "Everything happens for a reason, even if it takes time to realize it", "Strive not to be a success, but rather to be of value", "The only person you are destined to become is the person you decide to be", "Believe you can and you’re halfway there", "Life is not measured by the number of breaths we take, but by the moments that take our breath away", "Happiness is not something readymade. It comes from your own actions", "It is never too late to be what you might have been", "Dream big and dare to fail", "Our greatest glory is not in never falling, but in rising every time we fall.", "Live the life you have imagined", "Don't be afraid to take the first step", "If you were looking for a sign, this is it", "Life is too short to live the same day twice", "The past cannot be changed. The future is yet in your power", "Don't let yesterday take up too much of today", "What you want exists, don't settle until you get it", "Your potential is endless", "Wear your failure as a badge of honor", "Your past does not equal your future"]
  
  static let fonts = ["Noteworthy-Bold", "ChalkboardSE-Bold", "MarkerFelt-Wide", "AmericanTypewriter-Bold", "Avenir-Heavy", "Courier-Bold", "Futura-Medium"]
}
